---
version: '3.6'
services:
  wg-portal:
    build: .
    container_name: wg-portal
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
    environment:
      - EXTERNAL_URL=http://localhost:8123
      - CONFIG_FILE=/app/data/config.yml
